ESA-WEED-project/eo_processing

src/eo_processing/utils/messaging.py
This commit introduces a new messaging utility module for sending emails using an SMTP server. It includes functionality for formatting email addresses, sending emails to recipients (either directly or loaded from a file), and reading recipient details from a file. Appropriate error handling is implemented for file operations and malformed inputs.
=> Add email utility for sending and managing recipient lists

src/eo_processing/utils/messaging.py
Replaced the sender email address to use the 'vito.be' domain for consistency. Removed unnecessary blank lines to improve code clarity and formatting in the messaging utility.
=> Update sender email domain in messaging utility

src/eo_processing/utils/jobmanager.py
Introduced a new parameter `viz_edge_color` to the `DownloadManager` class, allowing users to specify the edge color in plots. Updated the relevant visualization logic to use this customizable parameter for enhanced flexibility. Default edge color remains 'black' for backward compatibility.
=> Add support for customizable edge color in visualization

src/eo_processing/utils/jobmanager.py
Introduce a `dl_cancel_time` parameter to set a timeout for download cancellations, making the class more configurable. Updated constructor docstrings to reflect the new parameter and provide clearer descriptions of class options.
=> Add `dl_cancel_time` parameter to `DownloadManager`

src/eo_processing/utils/helper.py
Corrected the misspelled 'cdse-stagging' in the helper function to ensure accurate backend connections for the staging environment. This prevents potential misconfigurations or runtime issues.
=> Fix typo in 'cdse-stagging' connection URL condition

src/eo_processing/utils/jobmanager.py
Modified the logic to track the running start time for jobs transitioning to either "running" or "finished" states. This ensures accurate tracking when the running start time was previously unset.
=> Update job status handling to include finished state

src/eo_processing/utils/jobmanager.py
Renamed and added new job statuses to the color mapping in `jobmanager.py` for improved status tracking. Introduced a default 'black' color for unmapped statuses to prevent potential errors. These changes enhance the visualization and error handling of job status updates.
=> Update job status colors and handle missing mappings

src/eo_processing/utils/jobmanager.py
Adjusted the default plot size to 10x10 inches and increased DPI to 200 for better clarity in notebook visualizations. Updated error status colors for improved readability and ensured map plots maintain an equal aspect ratio.
=> Set plot size, DPI, and color updates for job manager

src/eo_processing/config/settings.py
Adjusted the logic in `get_job_options` to support task-specific configurations, particularly for 'inference' when using the CDSE provider. Introduced `OPENEO_INFERENCE_CDSE_JOB_OPTIONS` for inference-specific resource allocation. Reduced the `max-executors` value in default settings for better resource management.
=> Update job options logic and add inference-specific settings

src/eo_processing/config/settings.py
Introduced `OPENEO_POINTEXTRACTION_CDSE_JOB_OPTIONS` to specify resource configurations for CDSE point extraction. Updated the job options retrieval logic to support `point_extraction` tasks, ensuring proper handling in CDSE workflows.
=> Add job options for CDSE point extraction tasks.

notebooks/alpha-1/pipeline_step5_inference-openEO.ipynb
The inference notebook was cleaned up by removing redundant cells, imports, and details. This reduction decreases the total notebook size from 852 to 331 lines, improving readability and maintainability while keeping core functionality intact.
=> Reduce pipeline inference notebook size significantly

requirements.txt, setup.py, src/eo_processing/_version.py, src/eo_processing/utils/metadata.py
Pinned `openeo` dependency to a specific version, updated the package version to `0.2.2`, and introduced a utility for generating metadata for GeoTiff outputs. These changes ensure compatibility, proper version tracking, and improved metadata support for the WEED project.
=> Update dependencies, bump version, and add metadata utility.

src/eo_processing/utils/storage.py
Renamed and generalized the `get_onnx_urls` method to `get_file_urls`, allowing retrieval of file URLs based on any specified extension. Updated logic to replace the hardcoded '.onnx' extension with a configurable parameter, improving flexibility and reuse. Removed the `_extract_onnx_urls` helper function, consolidating its functionality into the main method.
=> Refactor file URL retrieval to support custom extensions.

scripts/global_20x20km_UTM_tiling-grid.py
Replaced the 'epsg' key with 'crs' in the output dictionary for consistency and clarity. This ensures better alignment with standard naming practices for coordinate reference systems.
=> Update key 'epsg' to 'crs' in return dictionary

src/eo_processing/openeo/preprocessing.py
Addressed an issue where datasets lacking VH polarization were not processed correctly. Added a condition to filter collections with both VV and VH polarizations. This ensures proper data selection and avoids potential errors in downstream processing.
=> Fix handling of missing VH data in preprocessing

notebooks/AOI_tiling_for_jobmanager.ipynb, src/eo_processing/_version.py, src/eo_processing/openeo/masking.py, src/eo_processing/openeo/preprocessing.py, src/eo_processing/openeo/processing.py, src/eo_processing/utils/catalogue_check.py, src/eo_processing/utils/data_formats.py, src/eo_processing/utils/geoprocessing.py, src/eo_processing/utils/helper.py
Introduce a new `AOI_tiler` function to handle tiling of AOIs based on various input formats and grids. Modularize the `openEO_bbox_format` type by moving it to a separate `data_formats` module for better reusability. Update related modules to reflect these changes and increment the version to 0.2.7.
=> Add AOI tiling functionality and improve modularity

src/eo_processing/utils/geoprocessing.py
Replace `LAEA-20km.gpkg` with `LAEA-20km_add-info.gpkg` to ensure updated grid data is used. This change affects the EU tiling grid path and aligns with resource file modifications. Updated file provides additional information for improved geoprocessing accuracy.
=> Update tiling grid file reference in geoprocessing utility

src/eo_processing/config/settings.py
Introduced `OPENEO_CUBEEXTRACTION_CDSE_JOB_OPTIONS` for configuring cube extraction tasks. Updated task handling logic to apply these options when `feature_generation` is executed. This ensures better resource allocation and task-specific optimization.
=> Add job options for cube extraction in configuration

src/eo_processing/openeo/preprocessing.py
Ensure that the catalogue_check logic for the CDSE provider only applies when a bounding box (bbox) is provided. This prevents unnecessary evaluations and aligns the behavior with expected conditions.
=> Refine CDSE provider condition with bbox check.

setup.py
This is done to avoid specifying the requirements in both requirements.txt and setup.py.
=> Refactor setup.py

src/eo_processing/_version.py, src/eo_processing/utils/jobmanager.py
I use Version: 0.42.1 of the Client API for openEO
=> replace utcnow by now_utc in job_manager
